export const categories = [
  {
    id: 1,
    img: "",
    title: "Yoghurt",
    cat: "yoghurt",
  },
  {
    id: 2,
    img: "",
    title: "Milk",
    cat: "milk",
  },
  {
    id: 3,
    img: "",
    title: "Creams",
    cat: "cream",
  },
  {
    id: 4,
    img: "",
    title: "Butter",
    cat: "butter",
  },
  {
    id: 5,
    img: "",
    title: "Cheese",
    cat: "cheese",
  },
  {
    id: 6,
    img: "",
    title: "Mac Cuisine",
    cat: "mac-cuisine",
  },
];

export const products = [
  {
    _id: 1,
    category: "Yohgurt",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 2,
    category: "Yohgurt",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 3,
    category: "Milk",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 4,
    category: "Milk",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 5,
    category: "Yohgurt",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 6,
    category: "Yohgurt",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 7,
    category: "Yohgurt",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 8,
    category: "Yohgurt",
    sub_category: "",
    title: "Greek Yoghurt",
    price: 2000,
    desc: "some fairly long description",
    img: "",
  },
];
